image:
  name: atlassian/default-image:4

test: &test
  step:
    name: Test
    script:
      - npm install -g bats
      - chmod a+x test/*.bats
      - bats test/test.bats
    services:
      - docker

push: &push
  step:
    name: Push and Tag
    image: python:3.10
    script:
      #- source scripts/prBitbucketScripts/variables.sh
      #- source scripts/prBitbucketScripts/helperFns.sh
      #- source scripts/prBitbucketScripts/prBitbucketFindVersionTypeOrExitIfCommitMsgWrong.sh
      #- source scripts/prBitbucketScripts/prBitbucketVersionIncrease.sh
      - apt-get update && apt-get install -y awscli && apt-get install -y jq
      - ./release.sh
    services:
      - docker

pipelines:
  #default:
  #- <<: *test
  branches:
    master:
      #- <<: *test
      - <<: *push
