from __future__ import annotations

import importlib.util
import subprocess
import sys
import unittest
from pathlib import Path
from types import ModuleType
from unittest.mock import Mock, patch


SCRIPTS_DIR = Path(__file__).resolve().parents[1]


def load_module(module_name: str, file_name: str) -> ModuleType:
    script_path = str(SCRIPTS_DIR)
    if script_path not in sys.path:
        sys.path.insert(0, script_path)

    spec = importlib.util.spec_from_file_location(module_name, SCRIPTS_DIR / file_name)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module spec for {file_name}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


github_pr_shared = load_module("github_pr_shared_test_module", "github_pr_shared.py")


class GithubPrSharedTests(unittest.TestCase):
    def test_build_metadata_body_formats_summary_and_bullets(self) -> None:
        self.assertEqual(
            github_pr_shared.build_metadata_body(
                "Automated sync generated by workflow.",
                [("target branch", "master"), ("source sha", "abc123")],
            ),
            "Automated sync generated by workflow.\n\n"
            "- target branch: master\n"
            "- source sha: abc123\n",
        )

    @patch.object(github_pr_shared, "parse_repo_slug_from_remote_url")
    @patch.object(github_pr_shared, "extract_token_from_authenticated_remote_url")
    @patch.object(github_pr_shared, "try_direct_push_to_branch")
    @patch.object(github_pr_shared, "remote_branch_contains_local_head")
    def test_sync_current_head_to_protected_branch_via_pull_request_pushes_directly_when_allowed(
        self,
        mock_remote_contains_head: Mock,
        mock_try_direct_push_to_branch: Mock,
        mock_extract_token: Mock,
        mock_parse_slug: Mock,
    ) -> None:
        mock_remote_contains_head.return_value = False
        mock_try_direct_push_to_branch.return_value = True
        mock_extract_token.return_value = "test-token"
        mock_parse_slug.return_value = "carasent-asma/asma-argocd"
        run_command = Mock()

        result = github_pr_shared.sync_current_head_to_protected_branch_via_pull_request(
            repo_dir=Path("/tmp/asma-argocd"),
            remote_name="github",
            target_branch="master",
            remote_url="https://x-access-token:test-token@github.com/Carasent-ASMA/asma-argocd.git",
            source_branch_name="bot/argocd-sync/master-1234567890ab",
            title="asma-srv-auth.dev.version: 1234567.",
            body="sync body",
            merge_method="squash",
            subject_label="ArgoCD sync PR",
            run_command=run_command,
        )

        self.assertFalse(result.already_synced)
        self.assertTrue(result.pushed_directly)
        self.assertIsNone(result.pull_request)
        self.assertFalse(result.merged_immediately)
        mock_try_direct_push_to_branch.assert_called_once_with(
            Path("/tmp/asma-argocd"),
            "github",
            "master",
            run_command,
        )
        run_command.assert_not_called()

    @patch.object(github_pr_shared, "enable_pull_request_auto_merge")
    @patch.object(github_pr_shared, "try_merge_pull_request_immediately")
    @patch.object(github_pr_shared, "ensure_branch_allows_auto_merge")
    @patch.object(github_pr_shared, "create_or_reuse_pull_request")
    @patch.object(github_pr_shared, "try_direct_push_to_branch")
    @patch.object(github_pr_shared, "parse_repo_slug_from_remote_url")
    @patch.object(github_pr_shared, "extract_token_from_authenticated_remote_url")
    @patch.object(github_pr_shared, "remote_branch_contains_local_head")
    def test_sync_current_head_to_protected_branch_via_pull_request_merges_immediately(
        self,
        mock_remote_contains_head: Mock,
        mock_extract_token: Mock,
        mock_parse_slug: Mock,
        mock_try_direct_push_to_branch: Mock,
        mock_create_or_reuse_pull_request: Mock,
        mock_ensure_branch_allows_auto_merge: Mock,
        mock_try_merge_pull_request_immediately: Mock,
        mock_enable_pull_request_auto_merge: Mock,
    ) -> None:
        mock_remote_contains_head.return_value = False
        mock_extract_token.return_value = "test-token"
        mock_parse_slug.return_value = "carasent-asma/asma-argocd"
        mock_try_direct_push_to_branch.return_value = False
        pull_request = github_pr_shared.PullRequestInfo(
            number=42,
            node_id="PR_kwDOAAABBB4",
            url="https://github.com/Carasent-ASMA/asma-argocd/pull/42",
            head_ref="bot/argocd-sync/master-1234567890ab",
        )
        mock_create_or_reuse_pull_request.return_value = pull_request
        mock_try_merge_pull_request_immediately.return_value = (
            github_pr_shared.PullRequestMergeAttempt(
                merged=True,
                message="Merged",
            )
        )
        run_command = Mock(
            return_value=subprocess.CompletedProcess(
                args=["git", "push"],
                returncode=0,
                stdout="",
                stderr="",
            )
        )

        result = github_pr_shared.sync_current_head_to_protected_branch_via_pull_request(
            repo_dir=Path("/tmp/asma-argocd"),
            remote_name="github",
            target_branch="master",
            remote_url="https://x-access-token:test-token@github.com/Carasent-ASMA/asma-argocd.git",
            source_branch_name="bot/argocd-sync/master-1234567890ab",
            title="asma-srv-auth.dev.version: 1234567.",
            body="sync body",
            merge_method="squash",
            subject_label="ArgoCD sync PR",
            run_command=run_command,
        )

        self.assertFalse(result.already_synced)
        self.assertTrue(result.merged_immediately)
        self.assertEqual(result.pull_request, pull_request)
        self.assertFalse(result.pushed_directly)
        run_command.assert_called_once_with(
            [
                "git",
                "-C",
                "/tmp/asma-argocd",
                "push",
                "--force",
                "github",
                "HEAD:bot/argocd-sync/master-1234567890ab",
            ]
        )
        mock_create_or_reuse_pull_request.assert_called_once_with(
            "carasent-asma/asma-argocd",
            "bot/argocd-sync/master-1234567890ab",
            "master",
            "asma-srv-auth.dev.version: 1234567.",
            "sync body",
            "test-token",
            subject_label="ArgoCD sync PR",
        )
        mock_ensure_branch_allows_auto_merge.assert_not_called()
        mock_enable_pull_request_auto_merge.assert_not_called()

    def test_try_direct_push_to_branch_returns_false_for_protected_branch_rejection(
        self,
    ) -> None:
        run_command = Mock(
            return_value=subprocess.CompletedProcess(
                args=["git", "push"],
                returncode=1,
                stdout="",
                stderr=(
                    "remote: error: GH006: Protected branch update failed for refs/heads/master.\n"
                    "remote: error: Changes must be made through a pull request.\n"
                ),
            )
        )

        result = github_pr_shared.try_direct_push_to_branch(
            Path("/tmp/asma-argocd"),
            "github",
            "master",
            run_command,
        )

        self.assertFalse(result)

    def test_try_direct_push_to_branch_raises_for_unexpected_failure(self) -> None:
        run_command = Mock(
            return_value=subprocess.CompletedProcess(
                args=["git", "push"],
                returncode=1,
                stdout="",
                stderr="fatal: Authentication failed",
            )
        )

        with self.assertRaisesRegex(
            RuntimeError,
            "Direct branch push failed before PR fallback",
        ):
            github_pr_shared.try_direct_push_to_branch(
                Path("/tmp/asma-argocd"),
                "github",
                "master",
                run_command,
            )

    @patch.object(github_pr_shared, "get_pull_request_state")
    @patch.object(github_pr_shared, "try_merge_pull_request_immediately")
    @patch.object(github_pr_shared, "github_request")
    def test_enable_pull_request_auto_merge_tolerates_clean_status_for_merged_pr(
        self,
        mock_github_request: Mock,
        mock_try_merge_pull_request_immediately: Mock,
        mock_get_pull_request_state: Mock,
    ) -> None:
        mock_github_request.return_value = {
            "errors": [
                {
                    "message": "Pull request Pull request is in clean status",
                }
            ]
        }
        mock_try_merge_pull_request_immediately.return_value = (
            github_pr_shared.PullRequestMergeAttempt(
                merged=False,
                message="Pull request is already processed",
            )
        )
        mock_get_pull_request_state.return_value = ("closed", True)

        github_pr_shared.enable_pull_request_auto_merge(
            github_pr_shared.PullRequestInfo(
                number=82,
                node_id="PR_kwDOAAABBB4",
                url="https://github.com/Carasent-ASMA/asma-modules/pull/82",
                head_ref="bot/pointer/shared-asma-ui-table-8c7d625a1a3f",
            ),
            "token",
            "squash",
        )

        mock_try_merge_pull_request_immediately.assert_called_once_with(
            "carasent-asma/asma-modules",
            github_pr_shared.PullRequestInfo(
                number=82,
                node_id="PR_kwDOAAABBB4",
                url="https://github.com/Carasent-ASMA/asma-modules/pull/82",
                head_ref="bot/pointer/shared-asma-ui-table-8c7d625a1a3f",
            ),
            "token",
            "squash",
        )
        mock_get_pull_request_state.assert_called_once_with(
            "carasent-asma/asma-modules",
            82,
            "token",
        )

    @patch.object(github_pr_shared, "remote_branch_contains_local_head")
    def test_sync_current_head_to_protected_branch_via_pull_request_skips_when_synced(
        self,
        mock_remote_contains_head: Mock,
    ) -> None:
        mock_remote_contains_head.return_value = True
        run_command = Mock()

        result = github_pr_shared.sync_current_head_to_protected_branch_via_pull_request(
            repo_dir=Path("/tmp/asma-argocd"),
            remote_name="github",
            target_branch="master",
            remote_url="https://x-access-token:test-token@github.com/Carasent-ASMA/asma-argocd.git",
            source_branch_name="bot/argocd-sync/master-1234567890ab",
            title="asma-srv-auth.dev.version: 1234567.",
            body="sync body",
            merge_method="squash",
            subject_label="ArgoCD sync PR",
            run_command=run_command,
        )

        self.assertTrue(result.already_synced)
        self.assertIsNone(result.pull_request)
        self.assertFalse(result.merged_immediately)
        run_command.assert_not_called()


if __name__ == "__main__":
    unittest.main()
